name: Ejecutar run.py de Simulacion_Agentes

# Disparadores del workflow
on:
  push:
    branches: [ main ]  
  schedule:
    - cron: '0 0 * * *' 

jobs:
  run-script:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        working-directory: Simulacion_Agentes/project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar run.py
        working-directory: Simulacion_Agentes/project
        run: |
          python run.py
