name: Ejecutar run.py de Simulacion_Agentes

on:
  push:
    branches: [ main ]  
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a medianoche UTC

jobs:
  run-script:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        working-directory: Simulacion_Agentes/project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar run.py y guardar logs
        working-directory: Simulacion_Agentes/project
        run: |
          python run.py > run_log.txt 2>&1

      - name: Guardar log como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: run_log
          path: Simulacion_Agentes/project/run_log.txt
